Support custom domains
vitejs/vite-plugin-basic-ssl pull request #22
Opened 2023-12-29 10:46 UTC by gz65555

This PR introduces the following features: 
1. Custom domains
2. Custom cert directory
3. Custom name of certification

Can be easily set by:
```js
// vite.config.js
import basicSsl from '@vitejs/plugin-basic-ssl'

export default {
  plugins: [
    basicSsl({name: "test", domains: ["*.custom.com"], certDir: "/Users/.../.devServer/cert"})
  ]
}
```

Some essential options can make our local development more comfortable. In Chrome, there will not be unfriendly security warnings.

2023-12-31 21:04 UTC, sarim commented
It'd be nice to have this feature. 
Building on top of it, providing rootCA to use for signing would be nice. (I have my own rootCA that is trusted in my devices) I can work on that after this is merged.

2024-01-10 05:46 UTC, bluwy requested changes
The general idea sounds fine to me besides some comments below. We'd also need documentation for the new options though.

2024-01-10 05:46 UTC, bluwy commented on package.json
> +  "type": "module",
Can this be reverted? It'll break the types interpretation by TypeScript.

2024-01-10 05:46 UTC, bluwy commented on src/certificate.ts
> -    // },
And revert this? It would be nice to reduce the unrelated changes here.

2024-01-10 05:46 UTC, bluwy commented on src/certificate.ts
> -        },
And revert this

2024-01-10 10:03 UTC, gz65555 commented
@bluwy Thank you for reviewing, modifications are done.

2024-01-11 03:26 UTC, gz65555 commented
The options are quite simple, so I just update readme and add some comments on the options.

2024-01-11 16:35 UTC, sarim commented
I guess getCertificate function is exported for testing?

2024-01-11 17:16 UTC, patak-dev commented
> I guess getCertificate function is exported for testing?

It isn't used in the tests, no?

2024-01-11 18:38 UTC, sarim commented
@patak-dev https://github.com/vitejs/vite-plugin-basic-ssl/blob/17ddf64230e60861e57ec8d2f7799058d75ef671/test/test.spec.ts#L2

2024-01-15 04:39 UTC, bluwy approved these changes
Looks great to me! Thanks for making the changes. My only question I guess is maybe we should rename `certDir` to `cacheDir`. Since `certDir` could mean the directory if you generated the certificates yourself and we respect that (which we don't). But not too concerned of the naming either since it's a low maintenance package. 

About the `getCertificate`, perhaps we can remove that in the next major if we want to.

2024-01-15 08:25 UTC, patak-dev approved these changes

2024-01-15 08:27 UTC, patak-dev commented
Let's release a minor then to have this feature and support for Vite 5

@bluwy, would you expand on
> My only question I guess is maybe we should rename certDir to cacheDir. Since certDir could mean the directory if you generated the certificates yourself and we respect that (which we don't).

I didn't get that, `certDir` sounds good here. We should rename `cacheDir` to `certDir` in `getCertificate` to me 🤔

2024-01-15 08:28 UTC, merged

2024-01-15 10:01 UTC, bluwy commented
> I didn't get that, `certDir` sounds good here. We should rename `cacheDir` to `certDir` in `getCertificate` to me 🤔

`certDir` technically is used more as a cache. And the other options didn't have the `cert` prefix, meaning they're implicitly cert related already. So I figured `cacheDir` was clearer.

2024-01-15 10:08 UTC, patak-dev commented
Ah, I see. `cacheDir` may confuse some folks with the Vite cache dir. But I understand your point. Let's leave it for now then 👍🏼